x-common:
  &common
  image: apache/airflow:2.6.0
  user: "${AIRFLOW_UID}:0"
  env_file: 
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: airflow-redis
    image: redis:6

  scheduler:
    <<: [*common, *depends-on]
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"

  webserver:
    <<: [*common, *depends-on]
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
  
  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version

  
  airflow-worker-0:
    container_name: airflow-worker-0
    <<: [*common, *depends-on]
    command: airflow celery worker
  
  airflow-worker-1:
    container_name: airflow-worker-1
    <<: [*common, *depends-on]
    command: airflow celery worker
  
  airflow-worker-2:
    container_name: airflow-worker-2
    <<: [*common, *depends-on]
    command: airflow celery worker
  
  airflow-worker-3:
    container_name: airflow-worker-3
    <<: [*common, *depends-on]
    command: airflow celery worker
  
  airflow-worker-4:
    container_name: airflow-worker-4
    <<: [*common, *depends-on]
    command: airflow celery worker
  

volumes:
  postgres_data:
